In [10]:
import pandas as pd

In [11]:
import numpy as np

In [12]:
data=pd.read_csv("Data.csv")

In [13]:
display(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [15]:
data["Purchased"]=data["Purchased"].map({"Yes":1,"No":0})

In [16]:
display(data)

   Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
4  Germany  40.0      NaN          1
5   France  35.0  58000.0          1
6    Spain   NaN  52000.0          0
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [18]:
print(data.isnull().sum())

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [19]:
data["Salary"]=data["Salary"].fillna(data["Salary"].mean())

In [21]:
display(data)

   Country   Age        Salary  Purchased
0   France  44.0  72000.000000          0
1    Spain  27.0  48000.000000          1
2  Germany  30.0  54000.000000          0
3    Spain  38.0  61000.000000          0
4  Germany  40.0  63777.777778          1
5   France  35.0  58000.000000          1
6    Spain   NaN  52000.000000          0
7   France  48.0  79000.000000          1
8  Germany  50.0  83000.000000          0
9   France  37.0  67000.000000          1

In [22]:
data["Age"]=data["Age"].fillna(data["Age"].median())

In [23]:
display(data)

   Country   Age        Salary  Purchased
0   France  44.0  72000.000000          0
1    Spain  27.0  48000.000000          1
2  Germany  30.0  54000.000000          0
3    Spain  38.0  61000.000000          0
4  Germany  40.0  63777.777778          1
5   France  35.0  58000.000000          1
6    Spain  38.0  52000.000000          0
7   France  48.0  79000.000000          1
8  Germany  50.0  83000.000000          0
9   France  37.0  67000.000000          1